# Generated by Django 4.2.7 on 2023-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_isbn_alter_libro_numinvent'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name='Categoría'),
        ),
    ]
