# Generated by Django 4.2.7 on 2023-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Apellido y Nombre')),
                ('dni', models.BigIntegerField(max_length=200, verbose_name='DNI')),
                ('direccion', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('celular', models.BigIntegerField(verbose_name='Numero de Celular')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera')),
                ('imagen', models.ImageField(upload_to='clientes', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
