# Generated by Django 4.2.7 on 2023-11-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='carrera',
        ),
        migrations.AddField(
            model_name='clientes',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.BigIntegerField(verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombrelibro',
            field=models.CharField(max_length=200, verbose_name='Nombre del libro'),
        ),
    ]
