# Generated by Django 4.2.7 on 2023-11-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clientes_carrera_clientes_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='imagen',
        ),
    ]
