# Generated by Django 4.2.7 on 2023-11-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_clientes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.CharField(max_length=200, verbose_name='Correo electronico'),
        ),
    ]
