# Generated by Django 4.2.7 on 2023-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clientes_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cantidadDias',
            field=models.SmallIntegerField(default=7, verbose_name='Cantidad de Dìas a Reservar'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fechaPrestamo',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name='Categorìa'),
        ),
    ]
